# Generated by Django 5.2.17 on 2026-08-12 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_roles'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('customer_po_number', models.CharField(max_length=64)),
                ('customer_po_date', models.DateField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('destination_port', models.CharField(blank=True, max_length=100)),
                ('requested_shipment_date', models.DateField(blank=True, null=True)),
                ('planned_container_ready_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW — Ex Works'), ('FCA', 'FCA — Free Carrier'), ('CPT', 'CPT — Carriage Paid To'), ('CIP', 'CIP — Carriage and Insurance Paid To'), ('DAP', 'DAP — Delivered At Place'), ('DPU', 'DPU — Delivered At Place Unloaded'), ('DDP', 'DDP — Delivered Duty Paid'), ('FAS', 'FAS — Free Alongside Ship'), ('FOB', 'FOB — Free On Board'), ('CFR', 'CFR — Cost and Freight'), ('CIF', 'CIF — Cost, Insurance and Freight')], max_length=3)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('PACKING', 'Packing'), ('LOADING', 'Loading'), ('SHIPPED', 'Shipped'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=10)),
                ('internal_remarks', models.TextField(blank=True)),
                ('customer_remarks', models.TextField(blank=True)),
                ('bill_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customeraddress')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_orders', to='customers.customer')),
                ('export_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.employee')),
                ('ship_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customeraddress')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportOrderPOVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('document', models.FileField(upload_to='export_order_po_versions/')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_versions', to='export_orders.exportorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('export_order', 'version_number'), name='unique_po_version_number')],
            },
        ),
    ]
