# Generated by Django 5.2.17 on 2026-08-12 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0001_initial'),
        ('products', '0002_customerskumapping_carton_specification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(editable=False)),
                ('customer_sku_code', models.CharField(max_length=64)),
                ('customer_description', models.CharField(blank=True, max_length=255)),
                ('original_customer_quantity', models.PositiveIntegerField()),
                ('original_customer_unit', models.CharField(choices=[('PIECE', 'Pieces'), ('POUCH', 'Pouches'), ('CARTON', 'Cartons')], max_length=10)),
                ('pieces_per_pouch', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('pouches_per_carton', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='export_orders.exportorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_order_lines', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_number'],
                'constraints': [models.UniqueConstraint(fields=('export_order', 'line_number'), name='unique_export_order_line_number')],
            },
        ),
    ]
