# Generated by Django 5.2.17 on 2026-08-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
        ('export_orders', '0002_exportorderline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUSupplyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_from_stock', models.PositiveIntegerField(default=0)),
                ('quantity_to_produce', models.PositiveIntegerField(default=0)),
                ('quantity_to_procure', models.PositiveIntegerField(default=0)),
                ('is_intentionally_underplanned', models.BooleanField(default=False)),
                ('production_planned_start', models.DateField(blank=True, null=True)),
                ('production_expected_completion', models.DateField(blank=True, null=True)),
                ('procurement_planned_order_date', models.DateField(blank=True, null=True)),
                ('procurement_expected_receipt', models.DateField(blank=True, null=True)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('DELAYED', 'Delayed')], default='ON_TRACK', max_length=10)),
                ('planning_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_plan', to='export_orders.exportorderline')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.employee')),
                ('responsible_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
