# Generated by Django 5.2.17 on 2026-08-14 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
        ('export_orders', '0005_procurementrequirement_procurementtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportorderline',
            name='has_retail_sticker',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PackingMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_type', models.CharField(choices=[('CARTON', 'Cartons'), ('POUCH', 'Pouches'), ('RETAIL_STICKER', 'Retail Stickers'), ('BOX_LABEL', 'Box Labels')], max_length=20)),
                ('manual_required_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('ordered_qty', models.PositiveIntegerField(default=0)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('received_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_material_requirements', to='export_orders.exportorderline')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('export_order_line', 'material_type'), name='unique_packing_material_per_line')],
            },
        ),
    ]
