# Generated by Django 5.2.17 on 2026-08-14 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0006_exportorderline_has_retail_sticker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('CARTON_COMPLETED', 'Cartons Completed'), ('POUCH_PACKED', 'Pouches Packed')], max_length=20)),
                ('cartons_packed', models.PositiveIntegerField(blank=True, null=True)),
                ('pouches_packed', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_transactions', to='export_orders.exportorderline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
