# Generated by Django 5.2.17 on 2026-08-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0007_packingtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('PACKING', 'Packing'), ('READY_TO_LOAD', 'Ready to Load'), ('LOADING', 'Loading'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('planned_container_type', models.CharField(blank=True, max_length=64)),
                ('planned_ready_date', models.DateField(blank=True, null=True)),
                ('planned_stuffing_date', models.DateField(blank=True, null=True)),
                ('container_number', models.CharField(blank=True, max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='export_orders.exportorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_qty', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lines', to='export_orders.exportorderline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='export_orders.shipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
