# Generated by Django 5.2.17 on 2026-08-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0008_shipment_shipmentline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportorderline',
            name='stock_returned_cartons',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='actual_loaded_cartons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='variance_reason',
            field=models.CharField(blank=True, choices=[('CONTAINER_SPACE', 'Container space constraint'), ('CUSTOMER_APPROVED', 'Customer approved adjustment'), ('ADDITIONAL_SPACE', 'Additional space available'), ('PACKING_SHORTAGE', 'Packing shortage'), ('PRODUCT_SHORTAGE', 'Product shortage'), ('WEIGHT_RESTRICTION', 'Weight restriction'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
