# Generated by Django 5.2.17 on 2026-08-15 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0009_exportorderline_stock_returned_cartons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportorder',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('FULFILMENT', 'Fulfilment'), ('PACKING', 'Packing'), ('LOADING', 'Loading'), ('SHIPPED', 'Shipped'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=10),
        ),
        migrations.CreateModel(
            name='ExportOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='export_orders.exportorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportOrderStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('FULFILMENT', 'Fulfilment'), ('PACKING', 'Packing'), ('LOADING', 'Loading'), ('SHIPPED', 'Shipped'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='export_orders.exportorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
