# Generated by Django 5.2.17 on 2026-08-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0011_backfill_stage_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingmaterialrequirement',
            name='manual_to_procure_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
