# Generated by Django 5.2.17 on 2026-08-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0012_packingmaterialrequirement_manual_to_procure_qty'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementtransaction',
            name='party_team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productiontransaction',
            name='party_team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='procurementtransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.vendor'),
        ),
    ]
