# Generated by Django 5.2.17 on 2026-08-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
        ('export_orders', '0013_procurementtransaction_party_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtransaction',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='packingtransaction',
            name='shift_team',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
