# Generated by Django 5.2.17 on 2026-08-16 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_orders', '0014_packingtransaction_packed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('CARTON_LOADED', 'Cartons Loaded'), ('POUCH_LOADED', 'Pouches Loaded')], max_length=20)),
                ('cartons_loaded', models.PositiveIntegerField(blank=True, null=True)),
                ('pouches_loaded', models.PositiveIntegerField(blank=True, null=True)),
                ('variance_reason', models.CharField(blank=True, choices=[('CONTAINER_SPACE', 'Container space constraint'), ('CUSTOMER_APPROVED', 'Customer approved adjustment'), ('ADDITIONAL_SPACE', 'Additional space available'), ('PACKING_SHORTAGE', 'Packing shortage'), ('PRODUCT_SHORTAGE', 'Product shortage'), ('WEIGHT_RESTRICTION', 'Weight restriction'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_transactions', to='export_orders.shipmentline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
