# Generated by Django 5.2.17 on 2026-08-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mappings', '0003_migrate_customer_sku_mappings'),
        ('export_orders', '0018_repoint_product_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportorderline',
            name='source_mapping_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_order_lines', to='customer_mappings.customerproductmappingversion'),
        ),
    ]
