# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='code',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('STATION', 'Station'), ('MACHINE', 'Machine'), ('LOCATION', 'Location')], max_length=10),
        ),
    ]
