# Generated by Django 5.2.17 on 2026-08-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('materials', '0002_material_category'),
        ('processes', '0002_process_code_optional_resource_type'),
        ('products', '0005_product_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_definitions', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('resource_type', models.CharField(blank=True, choices=[('STATION', 'Station'), ('MACHINE', 'Machine'), ('LOCATION', 'Location')], max_length=10)),
                ('batch_lot_mode', models.CharField(choices=[('DISABLED', 'Disabled'), ('OPTIONAL', 'Optional'), ('REQUIRED', 'Required')], default='OPTIONAL', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_versions', to='processes.processcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_versions', to='core.organization')),
                ('process_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processes.processdefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInputDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('input_type', models.CharField(choices=[('MATERIAL', 'Material'), ('WIP', 'WIP'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], max_length=10)),
                ('uom', models.CharField(max_length=20)),
                ('quantity_capture', models.CharField(choices=[('MANUAL', 'Manual'), ('FORMULA', 'Formula'), ('OPTIONAL', 'Optional')], default='MANUAL', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_inputs', to='core.organization')),
                ('process_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='processes.processdefinitionversion')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.AddConstraint(
            model_name='processdefinitionversion',
            constraint=models.UniqueConstraint(fields=('process_definition', 'version_number'), name='unique_version_per_definition'),
        ),
        migrations.AddConstraint(
            model_name='processinputdefinition',
            constraint=models.UniqueConstraint(fields=('process_version', 'sequence'), name='unique_input_sequence_per_version'),
        ),
    ]
