# Generated by Django 5.2.17 on 2026-08-20 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('materials', '0002_material_category'),
        ('processes', '0003_processdefinition_processdefinitionversion_and_more'),
        ('products', '0005_product_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_classifications', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'output classifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessOutputDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('MATERIAL', 'Material'), ('PRODUCT', 'Product')], max_length=10)),
                ('uom', models.CharField(max_length=20)),
                ('can_move_forward', models.BooleanField(default=True)),
                ('creates_traceable_output', models.BooleanField(default=True)),
                ('default_storage_destination', models.CharField(blank=True, max_length=100)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_outputs', to='processes.outputclassification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='materials.material')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_outputs', to='core.organization')),
                ('process_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='processes.processdefinitionversion')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('process_version', 'sequence'), name='unique_output_sequence_per_version')],
            },
        ),
    ]
