# Generated by Django 5.2.17 on 2026-08-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_seed_output_classifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdefinitionversion',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='operator_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='standard_rate_config_level',
            field=models.CharField(blank=True, choices=[('PROCESS', 'Process level'), ('WORK_CENTRE', 'Work Centre level'), ('TOOLING_POSITION', 'Tooling / Position level')], max_length=20),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='work_centre_requirement',
            field=models.CharField(blank=True, choices=[('MACHINE', 'Machine'), ('STATION', 'Station'), ('EITHER', 'Machine or Station'), ('NONE', 'No work centre required')], max_length=10),
        ),
    ]
