# Generated by Django 5.2.17 on 2026-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_work_centre_step_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_different_sku_per_position',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_work_centre_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='capture_mode',
            field=models.CharField(blank=True, choices=[('WORK_CENTRE_TOTAL', 'One total for the work centre'), ('POSITION_LEVEL', 'Separate output from parallel positions'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='default_position_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='position_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
