# Generated by Django 5.2.17 on 2026-08-20 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('processes', '0007_output_capture_step_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_manual_standard_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='reserve_machine_derived_rate',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProcessParameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('BOOLEAN', 'Boolean'), ('SELECT', 'Select'), ('REFERENCE', 'Reference'), ('DATE', 'Date'), ('DATETIME', 'Date & Time')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('capture_at', models.CharField(choices=[('SETUP', 'Setup'), ('START', 'Start'), ('DURING', 'During'), ('COMPLETION', 'Completion')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_parameters', to='core.organization')),
                ('process_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='processes.processdefinitionversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('process_version', 'sequence'), name='unique_parameter_sequence_per_version'), models.UniqueConstraint(fields=('process_version', 'code'), name='unique_parameter_code_per_version')],
            },
        ),
    ]
