# Generated by Django 5.2.17 on 2026-08-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_parameters_step_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_correction_with_audit_trail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_destructive_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='allow_over_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='completion_mode',
            field=models.CharField(choices=[('OPERATOR', 'Operator marks transaction complete'), ('TARGET_REACHED', 'Target quantity reached')], default='OPERATOR', max_length=15),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='input_consumption_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual capture'), ('FORMULA', 'Formula driven'), ('FUTURE_INVENTORY', 'Future inventory integration')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='over_production_tolerance_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='partial_output_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='permit_machine_generated_source',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='qc_requirement',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUIRED', 'QC required before output can move forward')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='processdefinitionversion',
            name='transaction_frequency',
            field=models.CharField(blank=True, choices=[('SHIFT', 'Shift based'), ('BATCH', 'Batch based'), ('MANUAL', 'Manual entry'), ('MACHINE', 'Machine driven')], max_length=10),
        ),
    ]
