# Generated by Django 5.2.17 on 2026-09-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('packing_lite', '0002_packingallotment'),
        ('processes', '0011_processexecution_processexecutioninput_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCentreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pouches_packed', models.PositiveIntegerField(default=0)),
                ('allotment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centre_records', to='packing_lite.packingallotment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lite_record', to='processes.processexecution')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lite_work_centre_records', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
