# Generated by Django 5.2.17 on 2026-09-15 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('packing_lite', '0006_packingdayclosure_boxing_reconciliation_boxingrecord'),
        ('product_routes_v1', '0001_initial'),
        ('work_centres', '0008_alter_workcentre_operator_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCentreRouteNodeV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lite_work_centre_route_nodes_v1', to='core.organization')),
                ('route_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product_routes_v1.processroutenodev1')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lite_route_node_v1', to='work_centres.workcentre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
