# Generated by Django 5.2.17 on 2026-08-21 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sequence'),
        ('processes', '0009_rules_step_fields'),
        ('products', '0005_product_stage'),
        ('work_centres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tooling_type', models.CharField(choices=[('MOULD', 'Mould'), ('DIE', 'Die'), ('JIG', 'Jig'), ('FIXTURE', 'Fixture'), ('CUTTING_TOOL', 'Cutting Tool'), ('FORMING_TOOL', 'Forming Tool'), ('OTHER', 'Other')], max_length=15)),
                ('cavity_count', models.PositiveIntegerField(blank=True, null=True)),
                ('default_standard_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooling', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tooling',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCentrePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_index', models.PositiveIntegerField()),
                ('display_label', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centre_positions', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='work_centres.workcentre')),
            ],
            options={
                'ordering': ['position_index'],
            },
        ),
        migrations.CreateModel(
            name='ToolingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooling_assignments', to='core.organization')),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tooling.tooling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_centre_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tooling.workcentreposition')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ToolingCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tooling_compatibilities', to='core.organization')),
                ('process_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes.processdefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product')),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='tooling.tooling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tooling__name'],
                'constraints': [models.UniqueConstraint(fields=('tooling', 'product', 'process_definition'), name='unique_compatibility_per_tooling_product_process')],
            },
        ),
        migrations.AddConstraint(
            model_name='workcentreposition',
            constraint=models.UniqueConstraint(fields=('work_centre', 'position_index'), name='unique_position_per_work_centre'),
        ),
    ]
