# Generated by Django 5.2.17 on 2026-08-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0004_finalize_tooling_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingassignment',
            name='work_centre_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tooling.workcentreposition'),
        ),
    ]
