# Generated by Django 5.2.17 on 2026-08-22 16:54

import apps.customer_mappings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sequence'),
        ('customers', '0002_rename_postal_code_customeraddress_pin_and_more'),
        ('items', '0003_migrate_material_product_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PLATE_IMAGE', 'Plate Image'), ('POUCH_IMAGE', 'Pouch Image'), ('DESIGN_FILE', 'Design File'), ('RETAIL_STICKER_IMAGE', 'Retail Sticker Image')], max_length=32)),
                ('file', models.FileField(upload_to='customer_mapping_files/', validators=[apps.customer_mappings.models.validate_upload_file_size, apps.customer_mappings.models.validate_upload_file_type])),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LABEL', 'Label'), ('DOCUMENT', 'Document'), ('QUALITY', 'Quality'), ('PALLET', 'Pallet'), ('COMPLIANCE', 'Compliance'), ('OTHER', 'Other')], max_length=12)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='customers.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_mappings', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_mappings', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer__name', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProductMappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('customer_sku', models.CharField(max_length=64)),
                ('customer_description', models.CharField(blank=True, max_length=255)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='customer_mappings.customerproductmapping')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_mapping_versions', to='core.organization')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
