# Generated by Django 5.2.17 on 2026-08-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sequence'),
        ('customer_mappings', '0001_initial'),
        ('items', '0003_migrate_material_product_to_item'),
        ('packaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductmappingversion',
            name='packaging_profile_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_mapping_versions', to='packaging.packagingprofileversion'),
        ),
        migrations.AddField(
            model_name='customerproductmappingversion',
            name='selling_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.uom'),
        ),
        migrations.AddField(
            model_name='customerproductmappingversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappingfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappingfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappingfile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer_mappings.customerproductmappingversion'),
        ),
        migrations.AddField(
            model_name='mappingrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappingrequirement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_requirements', to='core.organization'),
        ),
        migrations.AddField(
            model_name='mappingrequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mappingrequirement',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='customer_mappings.customerproductmappingversion'),
        ),
        migrations.AddConstraint(
            model_name='customerproductmapping',
            constraint=models.UniqueConstraint(fields=('customer', 'item'), name='one_mapping_per_customer_item'),
        ),
        migrations.AddConstraint(
            model_name='customerproductmappingversion',
            constraint=models.UniqueConstraint(fields=('mapping', 'version_number'), name='unique_version_per_mapping'),
        ),
    ]
