# Generated by Django 5.2.17 on 2026-08-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mappings', '0004_customer_sku_discriminator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductmapping',
            name='mapping_code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
