# Generated by Django 5.2.17 on 2026-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, choices=[('RAW_MATERIAL', 'Raw Material'), ('PACKAGING', 'Packaging')], default='RAW_MATERIAL', max_length=20),
        ),
    ]
