# Generated by Django 5.2.17 on 2026-09-14 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sequence'),
        ('items', '0017_itemgroup_item_item_group'),
        ('processes_v1', '0001_initial'),
        ('product_routes', '0002_repoint_product_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRouteV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_v1', to='items.itemgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_routes_v1', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRouteVersionV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_route_versions_v1', to='core.organization')),
                ('process_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='product_routes_v1.processroutev1')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRouteNodeV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_key', models.CharField(max_length=64)),
                ('display_label', models.CharField(blank=True, max_length=255)),
                ('sequence_hint', models.PositiveIntegerField()),
                ('is_optional', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_route_nodes_v1', to='core.organization')),
                ('process_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes_v1.processdefinitionv1')),
                ('process_definition_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes_v1.processdefinitionversionv1')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='product_routes_v1.processrouteversionv1')),
            ],
            options={
                'ordering': ['sequence_hint'],
            },
        ),
        migrations.CreateModel(
            name='ProcessRouteItemMappingV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('input_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes_v1.processinputdefinitionv1')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_route_item_mappings_v1', to='core.organization')),
                ('output_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes_v1.processoutputdefinitionv1')),
                ('resolved_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='product_routes_v1.processroutenodev1')),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='product_routes_v1.processrouteversionv1')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRouteEdgeV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposition_type', models.CharField(choices=[('CONTINUE_TO_PROCESS', 'Continue to Process'), ('MOVE_TO_STORAGE', 'Move / Store')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product_routes.storagelocation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_route_edges_v1', to='core.organization')),
                ('source_output_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='processes_v1.processoutputdefinitionv1')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='product_routes_v1.processroutenodev1')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='product_routes_v1.processroutenodev1')),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='product_routes_v1.processrouteversionv1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='processrouteversionv1',
            constraint=models.UniqueConstraint(fields=('process_route', 'version_number'), name='unique_route_version_per_route_v1'),
        ),
        migrations.AddConstraint(
            model_name='processroutenodev1',
            constraint=models.UniqueConstraint(fields=('route_version', 'node_key'), name='unique_node_key_per_version_v1'),
        ),
        migrations.AddConstraint(
            model_name='processrouteitemmappingv1',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('input_definition__isnull', False), ('output_definition__isnull', True)), models.Q(('input_definition__isnull', True), ('output_definition__isnull', False)), _connector='OR'), name='exactly_one_definition_per_mapping'),
        ),
        migrations.AddConstraint(
            model_name='processrouteitemmappingv1',
            constraint=models.UniqueConstraint(condition=models.Q(('output_definition__isnull', False)), fields=('node', 'output_definition', 'target_item'), name='unique_output_mapping_per_target'),
        ),
        migrations.AddConstraint(
            model_name='processrouteitemmappingv1',
            constraint=models.UniqueConstraint(condition=models.Q(('input_definition__isnull', False)), fields=('node', 'input_definition', 'target_item'), name='unique_input_mapping_per_target'),
        ),
    ]
