# Generated by Django 5.2.17 on 2026-08-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_rules_step_fields'),
        ('work_centres', '0004_finalize_work_centre_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcentreprocesscapability',
            name='process_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centre_capabilities', to='processes.processdefinition'),
        ),
    ]
