# Generated by Django 5.2.17 on 2026-09-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_centres', '0006_bay_workcentre_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcentre',
            name='operator_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
