# Generated by Django 5.2.17 on 2026-09-10 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_centres', '0007_workcentre_operator_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcentre',
            name='operator_count',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
