from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

ROLE_NAMES = [
    "Export Coordinator",
    "Production Coordinator",
    "Procurement Coordinator",
    "Packing Coordinator",
    "Logistics Coordinator",
    "Manager/Admin",
    "Customer",
]

# (app_label, model_name, actions) that Manager/Admin can manage in Django admin.
MANAGER_ADMIN_PERMISSIONS = [
    ("core", "organization", ["add", "change", "view"]),
    ("accounts", "team", ["add", "change", "view"]),
    ("accounts", "employee", ["add", "change", "view"]),
]


def seed_roles(apps, schema_editor):
    # Auto-created model permissions (add_x/change_x/view_x) are normally
    # generated by a post_migrate signal that only fires after the whole
    # `migrate` run finishes — too late for this data migration to see them.
    # Force-create them now for the apps this migration needs permissions
    # from, using the real (non-historical) app registry.
    for app_config in global_apps.get_app_configs():
        if app_config.label in {"core", "accounts"}:
            create_permissions(app_config, verbosity=0, using=schema_editor.connection.alias)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    groups = {name: Group.objects.get_or_create(name=name)[0] for name in ROLE_NAMES}

    manager_admin = groups["Manager/Admin"]
    for app_label, model_name, actions in MANAGER_ADMIN_PERMISSIONS:
        for action in actions:
            try:
                permission = Permission.objects.get(
                    content_type__app_label=app_label,
                    codename=f"{action}_{model_name}",
                )
            except Permission.DoesNotExist:
                continue
            manager_admin.permissions.add(permission)


def remove_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ROLE_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_team_employee"),
        ("core", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(seed_roles, remove_roles),
    ]
