# Generated by Django 5.2.17 on 2026-08-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_sequence'),
        ('items', '0003_migrate_material_product_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('STANDARD', 'Standard'), ('CUSTOMER_TEMPLATE', 'Customer Template')], default='STANDARD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finished_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_profiles', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_profiles', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingProfileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('pack_mode', models.CharField(choices=[('PIECE', 'Piece'), ('POUCH', 'Pouch'), ('CARTON', 'Carton'), ('OTHER', 'Other')], default='PIECE', max_length=10)),
                ('pieces_per_pouch', models.PositiveIntegerField(blank=True, null=True)),
                ('pouches_per_carton', models.PositiveIntegerField(blank=True, null=True)),
                ('carton_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carton_breadth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carton_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carton_net_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carton_gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pieces_per_selling_unit', models.PositiveIntegerField(blank=True, null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_profile_versions', to='core.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packaging.packagingprofile')),
                ('selling_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.uom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PackagingProfileMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('POUCH', 'Pouch'), ('CARTON', 'Carton'), ('PALLET', 'Pallet'), ('OTHER', 'Other')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_profile_materials', to='core.organization')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.uom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='packaging.packagingprofileversion')),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='packagingprofileversion',
            constraint=models.UniqueConstraint(fields=('profile', 'version_number'), name='unique_version_per_profile'),
        ),
    ]
