# Generated by Django 5.2.17 on 2026-09-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_classification'),
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingprofileversion',
            name='recipe_scrap_item',
            field=models.ForeignKey(blank=True, help_text="This SKU's Scrap-grade sibling output.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_recipe_scrap_sibling', to='items.item'),
        ),
        migrations.AddField(
            model_name='packagingprofileversion',
            name='recipe_source_item',
            field=models.ForeignKey(blank=True, help_text='What this SKU is chopped/cut from (e.g. a raw leaf or a Template).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_recipe_source', to='items.item'),
        ),
        migrations.AddField(
            model_name='packagingprofileversion',
            name='recipe_standard_item',
            field=models.ForeignKey(blank=True, help_text="This SKU's Standard-grade sibling output.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_recipe_standard_sibling', to='items.item'),
        ),
        migrations.AddField(
            model_name='packagingprofileversion',
            name='recipe_trimmed_item',
            field=models.ForeignKey(blank=True, help_text='The trimmed WIP stage — what a Sorting/Cleaning/Packing process consumes as its input.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_recipe_trimmed', to='items.item'),
        ),
        migrations.AddField(
            model_name='packagingprofileversion',
            name='recipe_untrimmed_item',
            field=models.ForeignKey(blank=True, help_text='The untrimmed WIP stage, after Pressing, before Trimming.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_recipe_untrimmed', to='items.item'),
        ),
    ]
