# Generated by Django 5.2.17 on 2026-08-14 02:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

# Old free-form AddressType -> new Billing/Shipping/Billing & Shipping enum,
# per the "Customers - screen" spec revamp. "Other" has no direct
# equivalent — mapped to Billing & Shipping so no existing address becomes
# invisible to either the Bill To or Ship To picker.
_ADDRESS_TYPE_REMAP = {
    "BILL_TO": "BILLING",
    "SHIP_TO": "SHIPPING",
    "OTHER": "BILLING_AND_SHIPPING",
}


def remap_address_types(apps, schema_editor):
    CustomerAddress = apps.get_model("customers", "CustomerAddress")
    for old_value, new_value in _ADDRESS_TYPE_REMAP.items():
        CustomerAddress.objects.filter(address_type=old_value).update(address_type=new_value)


def reverse_remap_address_types(apps, schema_editor):
    CustomerAddress = apps.get_model("customers", "CustomerAddress")
    for old_value, new_value in _ADDRESS_TYPE_REMAP.items():
        CustomerAddress.objects.filter(address_type=new_value).update(address_type=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='postal_code',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='main_poc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('BILLING_AND_SHIPPING', 'Billing & Shipping')], max_length=21),
        ),
        # Widen the column before remapping, since BILLING_AND_SHIPPING (21
        # chars) doesn't fit the original varchar(10).
        migrations.RunPython(remap_address_types, reverse_remap_address_types),
    ]
