# Generated by Django 5.2.17 on 2026-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingplanline',
            name='plan_code',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
