# Generated by Django 5.2.17 on 2026-09-10 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('packing', '0002_packingplanline_plan_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingjob',
            name='status',
            field=models.CharField(choices=[('AWAITING_MATERIAL', 'Awaiting Material'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('STOPPED', 'Stopped'), ('CANCELLED', 'Cancelled')], default='AWAITING_MATERIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='PackingJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('START', 'Start'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('STOP', 'Stop'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel'), ('RESCHEDULE', 'Reschedule')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packing.packingjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_job_events', to='core.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
