# Generated by Django 5.2.17 on 2026-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_packingrecordingblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingintervalrecord',
            name='covers_unrecorded_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packingintervalrecord',
            name='is_final_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packingintervalrecord',
            name='record_type',
            field=models.CharField(choices=[('INTERVAL', 'Interval'), ('SUMMARY', 'Summary'), ('ADJUSTMENT', 'Adjustment')], default='INTERVAL', max_length=10),
        ),
    ]
