# Generated by Django 5.2.17 on 2026-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_specification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='other_packing_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pieces_per_pouch',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_specification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouches_per_carton',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='silica_gel_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='sticker_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
