# Generated by Django 5.2.17 on 2026-08-13 17:26

import apps.products.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customerskumapping_carton_specification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerskumapping',
            name='carton_specification',
        ),
        migrations.RemoveField(
            model_name='customerskumapping',
            name='pouch_specification',
        ),
        migrations.RemoveField(
            model_name='customerskumapping',
            name='silica_gel_requirement',
        ),
        migrations.RemoveField(
            model_name='customerskumapping',
            name='sticker_requirement',
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_net_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='carton_ply_rating',
            field=models.CharField(blank=True, choices=[('3_PLY', '3-ply'), ('5_PLY', '5-ply')], max_length=10),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='has_retail_sticker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='has_silica_gel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_breadth_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_height_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='pouch_thickness_microns',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerskumapping',
            name='retail_sticker_comments',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CustomerSKUMappingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PLATE_IMAGE', 'Plate Image'), ('POUCH_IMAGE', 'Pouch Image'), ('DESIGN_FILE', 'Design File'), ('RETAIL_STICKER_IMAGE', 'Retail Sticker Image')], max_length=32)),
                ('file', models.FileField(upload_to='customer_sku_mapping_files/', validators=[apps.products.models.validate_upload_file_size, apps.products.models.validate_upload_file_type])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer_sku_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.customerskumapping')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
