# Generated by Django 5.2.17 on 2026-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_customerskumapping_carton_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
