# Generated by Django 5.2.17 on 2026-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_available_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stage',
            field=models.CharField(blank=True, choices=[('SEMI_FINISHED', 'Semi-Finished'), ('FINISHED_GOOD', 'Finished Good')], default='FINISHED_GOOD', max_length=20),
        ),
    ]
