# Generated by Django 5.2.17 on 2026-08-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('items', '0003_migrate_material_product_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='breadth_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='short_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='producttype',
            name='short_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shapes', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'shapes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.shape'),
        ),
        migrations.CreateModel(
            name='NamingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_class', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('WIP', 'WIP'), ('FINISHED_GOOD', 'Finished Good'), ('PACKAGING_MATERIAL', 'Packaging Material'), ('CONSUMABLE', 'Consumable'), ('SCRAP_BY_PRODUCT', 'Scrap / By-Product')], max_length=20)),
                ('name_pattern', models.CharField(blank=True, max_length=255)),
                ('code_pattern', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naming_templates', to='core.organization')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.producttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_class', 'product_type__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product_type__isnull', False)), fields=('item_class', 'product_type'), name='unique_template_per_class_and_type'), models.UniqueConstraint(condition=models.Q(('product_type__isnull', True)), fields=('item_class',), name='unique_class_wide_template')],
            },
        ),
    ]
