# Generated by Django 5.2.17 on 2026-08-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_seed_shapes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namingtemplate',
            options={'ordering': ['item_class', 'product_type__name', 'shape__name']},
        ),
        migrations.RemoveConstraint(
            model_name='namingtemplate',
            name='unique_template_per_class_and_type',
        ),
        migrations.RemoveConstraint(
            model_name='namingtemplate',
            name='unique_class_wide_template',
        ),
        migrations.AddField(
            model_name='namingtemplate',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.shape'),
        ),
    ]
