# Generated by Django 5.2.17 on 2026-08-29 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_producttype_applicable_item_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='applicable_item_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('WIP', 'WIP'), ('FINISHED_GOOD', 'Finished Good'), ('PACKAGING_MATERIAL', 'Packaging Material'), ('CONSUMABLE', 'Consumable'), ('SCRAP_BY_PRODUCT', 'Scrap / By-Product')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
