# Generated by Django 5.2.17 on 2026-08-29 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sequence'),
        ('items', '0011_apply_items_mapping_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_class', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('WIP', 'WIP'), ('FINISHED_GOOD', 'Finished Good'), ('PACKAGING_MATERIAL', 'Packaging Material'), ('CONSUMABLE', 'Consumable'), ('SCRAP_BY_PRODUCT', 'Scrap / By-Product')], max_length=20)),
                ('field', models.CharField(choices=[('product_type', 'Product Type'), ('material_type', 'Material'), ('shape', 'Shape'), ('dimensions', 'Dimensions')], max_length=20)),
                ('state', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('HIDDEN', 'Hidden')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_field_rules', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_class', 'field'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'item_class', 'field'), name='unique_item_field_rule')],
            },
        ),
    ]
