# Generated by Django 5.2.17 on 2026-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_dimension_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='breadth_uom',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters'), ('MM', 'Millimeters')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height_uom',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters'), ('MM', 'Millimeters')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='length_uom',
            field=models.CharField(blank=True, choices=[('IN', 'Inches'), ('CM', 'Centimeters'), ('MM', 'Millimeters')], max_length=2, null=True),
        ),
    ]
